"use client";

import { TrendingUp } from "lucide-react";
import { LabelList, RadialBar, RadialBarChart } from "recharts";

import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import {
  ChartConfig,
  ChartContainer,
  ChartTooltip,
  ChartTooltipContent,
} from "@/components/ui/chart";

// Actor-based performance data
const chartData = [
  { actor: "Individual", reports: 275, fill: "var(--color-individual)" },
  { actor: "Supervisor", reports: 200, fill: "var(--color-supervisor)" },
  { actor: "Dept Head", reports: 187, fill: "var(--color-dept-head)" },
  { actor: "Vice Dean", reports: 173, fill: "var(--color-vice-dean)" },
  { actor: "President", reports: 90, fill: "var(--color-president)" },
];

const chartConfig = {
  reports: {
    label: "Reports",
  },
  individual: {
    label: "Individual",
    color: "hsl(var(--chart-1))",
  },
  supervisor: {
    label: "Supervisor",
    color: "hsl(var(--chart-2))",
  },
  deptHead: {
    label: "Department Head",
    color: "hsl(var(--chart-3))",
  },
  viceDean: {
    label: "Vice Dean",
    color: "hsl(var(--chart-4))",
  },
  president: {
    label: "President",
    color: "hsl(var(--chart-5))",
  },
} satisfies ChartConfig;

export default function RadialChartGraph() {
  return (
    <Card className="flex flex-col">
      <CardHeader className="items-center pb-0">
        <CardTitle>Radial Chart - Reports by Actors</CardTitle>
        <CardDescription>Performance Overview (Jan - Jun 2024)</CardDescription>
      </CardHeader>
      <CardContent className="flex-1 pb-0">
        <ChartContainer
          config={chartConfig}
          className="mx-auto aspect-square max-h-[250px]"
        >
          <RadialBarChart
            data={chartData}
            startAngle={-90}
            endAngle={380}
            innerRadius={30}
            outerRadius={110}
          >
            <ChartTooltip
              cursor={false}
              content={<ChartTooltipContent hideLabel nameKey="actor" />}
            />
            <RadialBar dataKey="reports" background>
              <LabelList
                position="insideStart"
                dataKey="actor"
                className="fill-white capitalize mix-blend-luminosity"
                fontSize={11}
              />
            </RadialBar>
          </RadialBarChart>
        </ChartContainer>
      </CardContent>
      <CardFooter className="flex-col gap-2 text-sm">
        <div className="flex items-center gap-2 font-medium leading-none">
          Trending up by 8.7% this quarter <TrendingUp className="h-4 w-4" />
        </div>
        <div className="leading-none text-muted-foreground">
          Total reports generated by actors (Jan - Jun 2024)
        </div>
      </CardFooter>
    </Card>
  );
}
